spring:
  jpa:
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: create


  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/spring
    username: sa
    password:
    driver-class-name: org.h2.Driver


logging:
  level:
    org.hibernate.SQL: debug